CREATE TABLE country_data (
    Country TEXT,
    "Density (P/Km2)" FLOAT,
    "Agricultural Land (%)" TEXT,
    "Land Area(Km2)" FLOAT,
    "Armed Forces size" FLOAT,
    "Birth Rate" FLOAT,
    "Co2-Emissions" FLOAT,
    CPI FLOAT,
    "CPI Change (%)" FLOAT,
    "Fertility Rate" FLOAT,
    "Forested Area (%)" FLOAT,
    "Gasoline Price" FLOAT,
    GDP FLOAT,
    "Gross primary education enrollment (%)" FLOAT,
    "Gross tertiary education enrollment (%)" FLOAT,
    "Infant mortality" FLOAT,
    "Life expectancy" FLOAT,
    "Maternal mortality ratio" FLOAT,
    "Minimum wage" FLOAT,
    "Out of pocket health expenditure" FLOAT,
    "Physicians per thousand" FLOAT,
    "Population" FLOAT,
    "Population: Labor force participation (%)" FLOAT,
    "Tax revenue (%)" FLOAT,
    "Total tax rate" FLOAT,
    "Unemployment rate" FLOAT,
    "Urban_population" FLOAT,
    "Latitude" FLOAT,
    "Longitude" FLOAT,
    "Urban Percentage" FLOAT,
    "Life expectancy group" int
);
select * from country_data;  

Drop TABLE country_data;


CREATE TABLE country_data (
    Country TEXT,
    "Density (P/Km2)" FLOAT,
    "Agricultural Land (%)" TEXT,
    "Land Area(Km2)" FLOAT,
    "Armed Forces size" FLOAT,
    "Birth Rate" FLOAT,
    "Co2-Emissions" FLOAT,
    CPI FLOAT,
    "CPI Change (%)" FLOAT,
    "Fertility Rate" FLOAT,
    "Forested Area (%)" FLOAT,
    "Gasoline Price" FLOAT,
    GDP FLOAT,
    "Gross primary education enrollment (%)" FLOAT,
    "Gross tertiary education enrollment (%)" FLOAT,
    "Infant mortality" FLOAT,
    "Life expectancy" FLOAT,
    "Maternal mortality ratio" FLOAT,
    "Minimum wage" FLOAT,
    "Out of pocket health expenditure" FLOAT,
    "Physicians per thousand" FLOAT,
    "Population" FLOAT,
    "Population: Labor force participation (%)" FLOAT,
    "Tax revenue (%)" FLOAT,
    "Total tax rate" FLOAT,
    "Unemployment rate" FLOAT,
    "Urban_population" FLOAT,
    "Latitude" FLOAT,
    "Longitude" FLOAT,
    "Urban Percentage" FLOAT,
    "Life expectancy group" int
);
SELECT * from country_data;
DROP TABLE country_data;
CREATE TABLE country_data (
    Country TEXT,
    "Density (P/Km2)" FLOAT,
    "Agricultural Land (%)" TEXT,
    "Land Area(Km2)" TEXT,
    "Armed Forces size" TEXT,
    "Birth Rate" TEXT,
    "Co2-Emissions" TEXT,
    CPI FLOAT,
    "CPI Change (%)" TEXT,
    "Fertility Rate" FLOAT,
    "Forested Area (%)" TEXT,
    "Gasoline Price" FLOAT,
    GDP FLOAT,
    "Gross primary education enrollment (%)" TEXT,
    "Gross tertiary education enrollment (%)" TEXT,
    "Infant mortality" FLOAT,
    "Life expectancy" FLOAT,
    "Maternal mortality ratio" FLOAT,
    "Minimum wage" FLOAT,
    "Out of pocket health expenditure" TEXT,
    "Physicians per thousand" FLOAT,
    "Population" TEXT,
    "Population: Labor force participation (%)" TEXT,
    "Tax revenue (%)" TEXT,
    "Total tax rate" FLOAT,
    "Unemployment rate" FLOAT,
    "Urban_population" FLOAT,
    "Latitude" FLOAT,
    "Longitude" FLOAT,
    "Urban Percentage" FLOAT,
    "Life expectancy group" int
);
DROP TABLE country_data;

CREATE TABLE country_data (
    Country TEXT,
    "Density (P/Km2)" TEXT,
    "Agricultural Land (%)" TEXT,
    "Land Area(Km2)" TEXT,
    "Armed Forces size" TEXT,
    "Birth Rate" TEXT,
    "Co2-Emissions" TEXT,
    CPI TEXT,
    "CPI Change (%)" TEXT,
    "Fertility Rate" FLOAT,
    "Forested Area (%)" TEXT,
    "Gasoline Price" TEXT,
    GDP TEXT,
    "Gross primary education enrollment (%)" TEXT,
    "Gross tertiary education enrollment (%)" TEXT,
    "Infant mortality" FLOAT,
    "Life expectancy" FLOAT,
    "Maternal mortality ratio" FLOAT,
    "Minimum wage" TEXT,
    "Out of pocket health expenditure" TEXT,
    "Physicians per thousand" FLOAT,
    "Population" TEXT,
    "Population: Labor force participation (%)" TEXT,
    "Tax revenue (%)" TEXT,
    "Total tax rate" TEXT,
    "Unemployment rate" TEXT,
    "Urban_population" TEXT,
    "Latitude" FLOAT,
    "Longitude" FLOAT,
    "Urban Percentage" TEXT,
    "Life expectancy group" int
);

SELECT * FROM country_data;